### ISSUE TITLE
[6.0.0-prerelease.7] Cannot find module './runner/cli'

### ISSUE THREAD

**Issue by chrismbeckett** [Polymer/web-component-tester#526]
I am able to test correctly with 6.0.0-prerelease.5, but after upgrading to 6.0.0-prerelease.7 I get the following error.

```
module.js:471
    throw err;
    ^

Error: Cannot find module './runner/cli'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Drive\Source\arsnebula\nebula-focus-behavior\node_modules\web-component-tester\runner.js:11:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Test failed.  See above for more details.
```
I am running on Windows 10, Node 6.10.2, and WCT 6.0.0-prerelease.7.

**Comment by kriscooke** [comment]
I first experienced this during an upgrade (global install) from 4.2.2 --> 5.0. I wonder if it could have something to do with the install? 🤔 

After uninstalling and trying to upgrade to different versions, I got this same error for any version above 4.2.2 (which is what I had been working with for some time).

Interestingly, 5.0 (or 6.0.0-prerelease.5, I can't tell which one is being run) _does_ seem to work absolutely fine via `polymer test` through Polymer CLI - but fails with the error when installing globally and running as `wct`.

```
# npm ls web-component-tester --global

├─┬ polymer-cli@0.17.0
│ └─┬ web-component-tester@5.0.0 
│   └─┬ test-fixture@3.0.0-rc.1 (git://github.com/polymerelements/test-fixture.git#eb86ce25c850bb20523d47a55d07235f0fad5858)
│     └── web-component-tester@6.0.0-prerelease.5 
└── web-component-tester@4.2.2  (git://github.com/Polymer/web-component-tester.git#7b5b808c165ddf469d261ffc1bf4d094ccb2a78c)
```

I'm running Node 6.8.0 on MacOS 10.

**Comment by rictic** [comment]
I believe this is an issue with the way that wct looks for a local installation of wct before running. I haven't been able to repro locally yet though.

This shouldn't block the release of 6.0.0 though.

**Comment by chrismbeckett** [comment]
I just tried out the 6.0.0 release and I can't reproduce the problem anymore, so it seems to be fixed.
